pipeline {
    agent any
    environment {
        DOCKER_FILE_PATH = "admin-processes/docker/Dockerfile"
    }
    parameters {
        string(defaultValue: "develop", description: '', name: 'branch_name_provided')
    }

    stages {
        stage('Build') {
            steps {
                // checkout scm  
                // git([url: 'git://example.com/amazing-project.git', branch: 'master'])
                // sh 'git clone https://github.com/PALMDEV/drproject.git'
                
                echo 'Building..'
                // TODO: use jenkins credentials for login and generate new credentials for it
                sh "docker login --username luisdavis --password pigui_02"
                // Build Enviroment
                sh "docker build -f DOCKER_FILE_PATH --target env -t luisdavis/drproject-enviroment:latest ."
                // Build QA
                //TODO: one for QA and Prod with conditionals on the build
                sh "docker build -f DOCKER_FILE_PATH --target prod -t luisdavis/drproject-prod:latest ."
                //TODO: add support for version tags to be able rollback a release
                
                //Docker push 
                sh "docker push luisdavis/drproject-enviroment:latest"
                sh "docker push luisdavis/drproject-prod:latest"
                setBuildStatus("In Progress","PENDING","Jenkins CI","${GIT_COMMIT}")
                
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'ng lint'
                // echo "${GITHUB_PR_NUMBER}" throws and error
                
            }
            post {
                failure {
                    echo "Test are failing"
                    setBuildStatus("Test are failing","FAILURE","Jenkins CI","${GIT_COMMIT}")
                    // error('least')
                }    
            }


        }
        stage('Deploy') { 
            when { branch "develop" }
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        success {
            echo "we dit it"
            setBuildStatus("Complete","SUCCESS","Jenkins CI","${GIT_COMMIT}")
        }
        failure {
            setBuildStatus("Complete","FAILURE","Jenkins CI","${GIT_COMMIT}")
            // mail to: 'team@example.com', subject: 'Pipeline failed', body: "${env.BUILD_URL}"
        }
    }

}

def setBuildStatus(String message, String state, String context, String sha) {
    step([
        $class: "GitHubCommitStatusSetter",
        reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/PALMDEV/drproject.git"],
        contextSource: [$class: "ManuallyEnteredCommitContextSource", context: context],
        errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
        commitShaSource: [$class: "ManuallyEnteredShaSource", sha: sha ],
        statusBackrefSource: [$class: "ManuallyEnteredBackrefSource", backref: "${BUILD_URL}flowGraphTable/"],
        statusResultSource: [$class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
    ]);
}